---
title: "Linear Models"
author: "Pavithra Srinivasan"
output: github_document
---

Loading Key Packages

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)

```

Lets fit a model!!
```{r}
  fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

Lets look at 'fit'
```{r}
summary(fit)
summary(fit)$coef
coef(fit)
fitted.values(fit)
```

Tidy up the output instead
```{r}
fit |>
  broom::glance()

```
Tidy up the coefficients
```{r}
fit |>
  broom::tidy() |>
  select(term, estimate, p.value) |> 
  mutate(term = str_replace(term, "^borough", "Borough: ")) |> 
  knitr::kable(digits = 3)

```

## Fit another model
```{r}
fit =
  nyc_airbnb |>
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  ) |>
  lm(price ~ stars + borough, data = _)

fit |>
  broom::tidy()
```

## Quick look at diagnostics
```{r}
nyc_airbnb |>
  modelr::add_residuals(fit) |>
  ggplot(aes(x = stars, y = resid)) +
  geom_violin()

nyc_airbnb |>
  modelr::add_residuals(fit) |>
  ggplot(aes(x = stars, y = resid)) +
  geom_point()
```

## Hypothesis test for categorial predictor

fit a "null" and "alternative" model

```{r}
fit_null = lm(price ~ stars + borough, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough + room_type, data = nyc_airbnb)

anova(fit_null, fit_alt) |>
  broom::tidy()
```

## Borough level differences









